[package]
name = "data_builder_for_operations_that_need_to_be_correct"
version = "0.1.0"
edition = "2024"

[dependencies]
#client_table_blueprints = { git = "https://github.com/Zakarias-Viinikka/ZakkeN", branch = "main" }
client_table_blueprints.path = "/home/zakke/ProgStuff/ZakkeN/client_table_blueprints"
#love_letter = { git = "https://github.com/Zakarias-Viinikka/ZakkeN", branch = "main" }
love_letter.path = "/home/zakke/ProgStuff/ZakkeN/love_letter"
#my_yrs_lib = { git = "https://github.com/Zakarias-Viinikka/ZakkeN", branch = "main", package = "yrs" }
yrs.path = "/home/zakke/ProgStuff/ZakkeN/yrs"
#protocol = { git = "https://github.com/Zakarias-Viinikka/z_db", branch = "main" }
protocol.path = "/home/zakke/ProgStuff/z_db/protocol"
#web_internal_db = { git = "https://github.com/Zakarias-Viinikka/z_db", branch = "main" }
web_internal_db.path = "/home/zakke/ProgStuff/z_db/web_internal_db"
error_stuff = { path = "../error_stuff" }
text_diff.path = "/home/zakke/ProgStuff/ZakkeN/text_diff"
