[package]
name = "fs5"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.20", features = ["csr"] }
leptos_router = "0.8.15"

leptos_integration_3 = { path = "../wasm/leptos_integration_3" }

random_word = { version = "0.5.2", features = ["en"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
