[package]
name = "executor_of_what_the_builder_built_because_the_builder_shouldnt_touch_the_db"
version = "0.1.0"
edition = "2024"

[dependencies]
error_stuff = { path = "/home/zakke/ProgStuff/ZakkeN/cqrs_state_synchronization/error_stuff" }
data_builder_for_operations_that_need_to_be_correct = { path = "/home/zakke/ProgStuff/ZakkeN/cqrs_state_synchronization/data_builder_for_operations_that_need_to_be_correct" }
protocol = { git = "https://github.com/Zakarias-Viinikka/z_db", branch = "main" }
web_internal_db = { git = "https://github.com/Zakarias-Viinikka/z_db", branch = "main" }
